### ISSUE TITLE
Memory cache does not work

### ISSUE THREAD

**Issue by stanley90** [jeopard/historical-bank-ruby#6]
Hi,
I noticed my exchange rate requests are taking too long, and found out that in [`get_base_rate`](https://github.com/jeopard/historical-bank-ruby/blob/c973c4277a395a00ad27a97b8408de849af431ee/lib/money/bank/historical.rb#L321), the date is a `Date` but the cache keys are `String`, so the value is never returned.
It works if it's changed this way: `rates[date.to_s] if rates`
(it's not possible to use a `String` argument, because it's expected to be a `Date` in `#datetime_to_date`.

**Comment by jeopard** [comment]
omg, what a bug!!! Thank you for spotting it @stanley90 !! I issued [a fix](https://github.com/jeopard/historical-bank-ruby/commit/20f213a043c0d06cc84ab037d416d9e874301cb9), and since it was quite significant, I put your name in the contributors as well! I pushed a new gem version. Thank you!

**Comment by stanley90** [comment]
Well yeah, it had a _huge_ negative impact on the stuff I'm working on and I was quite surprised when I found it 😀 Thanks for the quick fix!

**Comment by stanley90** [comment]
I'm reimplementing something which is quite slow for different reasons (bad design 😁), I wrote a prototype for it and a complete calculation took ~0.5s, then I added FX conversion, and whoa, it took 8s, so I started inspecting what gives, and found this. And yes, I'm also pretty surprised why the Redis fetch takes so long, but it's not only my machine, also on a server, this fix reduces the run time of a report from 120s to 50s... Anyway if I wasn't fiddling with the prototype, I would probably never have noticed.
